version: '3.7'

volumes:
  db:
    external: true

services:

  nginx:
      image: nginx:latest
      container_name: my-nginx
      restart: always
      ports:
        - "27017:27017"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      networks:
        - net
  database:
    container_name: database
    image: mongo:6.0.14  # ✅ รองรับ ARM64 / Mac M1+ อย่างสมบูรณ์
    platform: linux/arm64  # ✅ บังคับ platform
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - net

  database-admin:
    container_name: mongo_express_gui
    image: mongo-express:latest
    platform: linux/arm64/v8  # ✅ ระบุเพื่อความแน่นอนบน Mac ARM
    restart: always
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@database:27017/
      ME_CONFIG_SITE_BASEURL: /mongoadmin/
    ports:
      - 8081:8081
    networks:
      - net
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

networks:
  net:
    external: true
    driver: bridge
